apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
  namespace: minio
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: minio-client-job
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z
        command: [ "sh", "-c"]
        args:
          - |
            until mc config host add minio http://minio-service.minio:9000 minio minio123; do
              echo '...waiting...'
              sleep 5
            done 
            
            mc mb minio/datalake
            mc policy set public minio/datalake
      restartPolicy: Never
  backoffLimit: 4