apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: metastore
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine3.20
          env:
            - name: POSTGRES_DB
              value: metastore
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: metastore
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-volume
  volumeClaimTemplates:
    - metadata:
        name: postgres-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi