catalogs:
  iceberg: |-
    connector.name=iceberg
    fs.native-s3.enabled=true
    hive.metastore.uri=thrift://hive-service.metastore:9083
    s3.endpoint=http://minio-service.minio:9000
    s3.path-style-access=true
    s3.aws-access-key=minio
    s3.aws-secret-key=minio123
    s3.region=us-west-1
    iceberg.file-format=parquet